name: Updater file

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:

  updater:
    name: Updating the updater file
    runs-on: windows-latest
     
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Creating the file
        run: |
          echo "<?xml version="1.0" encoding="UTF-8"?><item><version>${{ github.event.release.tag_name }}.0</version><url>https://github.com/VordyV/NetBatLauncher/releases/download/${{ github.event.release.tag_name }}/NetBat2142.exe</url><changelog>https://github.com/VordyV/NetBatLauncher/releases/tag/${{ github.event.release.tag_name }}</changelog><mandatory>false</mandatory></item>" > update.xml

      - name: Commit and push file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add update.xml
          git commit -m "chore: add release info for ${{ github.ref_name }}" || echo "No changes"
          git push origin HEAD:${{ github.event.repository.default_branch }}
